var bios = [
{
  "name":"Alex,",
  "age": 23,
  "distance" : "3 miles away",
  "bio": "Live. Love. Jesus. Looking for someone with the same passion for JC as I do!",
  "correctAnswer": "Are you an angel because my world suddenly became brighter and lighter?",
  "answer2": "All I want for Channukah is you.",
  "answer3": "Even though I don't worship, you are the One for me.",
},
{
  "name":"Bobbie,",
  "age": 22,
  "distance" : "1 mile away",
  "bio": "Graphic Designer! I can code your website only if we get coffee sometime lol.",
  "correctAnswer": "You are like a semicolon, without you everything falls apart.",
  "answer2": "Life without you is like a broken pencil... pointless.",
  "answer3": "Let's convert our potential energy to kinetic energy.",
},
{
  "name":"Ari,",
  "age": 24,
  "distance" : "5 miles away",
  "bio": "If you’re not just as obsessed with Game of Thrones as I am, we can’t be friends..",
  "correctAnswer": "Did you get sacrificed by the God of Fire? Because you’re smoking!",
  "answer2": "I may not be the one who lived, but I can still be your chosen one.",
  "answer3": "Are you a Snitch? Because you’re the finest catch here.",
},
{
  "name":"Charlie,",
  "age": 20,
  "distance" : "5 miles away",
  "bio": "I LOVE cats. I’m okay with being 4ever alone with 50 cats, but maybe we can raise them 2gether?",
  "correctAnswer": "MEOW you doin?",
  "answer2": "Yeah, I like to chase my tail, but I’d much rather chase yours.",
  "answer3": "If you were vegetable, you’d be a cute-cumber.",
},
{
  "name":"Daryl,",
  "age": 28,
  "distance" : "4 miles away",
  "bio": "#420friendly #blazeitdon’tpraiseit #snoopdog dude, lets smoke.",
  "correctAnswer": "I have a huge kush on you.",
  "answer2": "Is it hot in here or is that just the Holy Spirit burning inside of you?",
  "answer3": "Are you a cigarette because you've got a hot butt.",
},
{
  "name":"Harley,",
  "age": 28,
  "distance" : "5 miles away",
  "bio": "Trying to become a professional baseball player. Go Red Sox!",
  "correctAnswer": "This match is a home run, huh?",
  "answer2": "If I were a soccer ball, would you kick it with me?",
  "answer3": "Hey, do you play Center? Because you are the center of my attention?",
},
{
  "name":"Ed,",
  "age": 22,
  "distance" : "1.1 miles away",
  "bio": "English major. Trying to become the next J.K.Rowling.",
  "correctAnswer": "If you were words on a page, you would be fine print.",
  "answer2": "Are you a bank loan because you got my interest.",
  "answer3": "If you were President, you'd be Babe-raham Lincoln.",
},
{
  "name":"Jesse,",
  "age": 28,
  "distance" : "1.5 miles away",
  "bio": "I love classical music. Trying to find someone to come with me to a jazz bar.",
  "correctAnswer": "You had me at cello!",
  "answer2": "I got my eyes on you, you're everything that I see..",
  "answer3": "Call me AC/DC, because I'm gonna rock your world!",
},
{
  "name":"Kyle,",
  "age": 28,
  "distance" : "2 miles away",
  "bio": "I love gaming:) especially Super Mario Bros.",
  "correctAnswer": "I don't need a mushroom for my love for you to grow.",
  "answer2": "Our love is like dividing by zero... you cannot define it.",
  "answer3": "Baby is your name pac-man ? Cause every time I see you I want to chase you.",
},
{
  "name":"Lou,",
  "age": 28,
  "distance" : "3 miles away",
  "bio": "Let’s spend our days together painting all day during sunset.",
  "correctAnswer": "You’re so fine you could make an impression on Monet.",
  "answer2": "I must be related to Ben Franklin. I've just discovered some electricity between us.",
  "answer3": "Are your eyes Ikea because I'm lost in them",
},
{
  "name":"Reed,",
  "age": 28,
  "distance" : "3 miles away",
  "bio": "I love being in nature. Let’s live in the forrest and save Mother Earth. ",
  "correctAnswer": "You're more precious than a recently-planted tree in a country with high levels of deforestation.",
  "answer2": "Are you a magician? Because whenever I look at you everyone else disappears.",
  "answer3": "Do you like raisins? How do you feel about a date?",
},
{
  "name":"Sam,",
  "age": 28,
  "distance" : "4.5 miles away",
  "bio": "Aspiring doctor. NYU. I might be able to save your life one day;)",
  "correctAnswer": "My doctor says I'm lacking vitamin U.",
  "answer2": "Do you work at Little Caesars? Because you're Hot and I'm Ready.",
  "answer3": "Baby you light up my world like my primary visual cortex.",
},
{
  "name":"Val,",
  "age": 28,
  "distance" : "1 mile away",
  "bio": "Gainz all day. No carbs diet. Looking for a gym partner so we can flex on everyone.",
  "correctAnswer": "Kissing burns 6.4 calories a minute. Wanna workout?",
  "answer2": "Is your body from McDonald's? 'cause I'm lovin' it!",
  "answer3": "I'm not an organ donor, but I'd be happy to give you my heart.",
},
{
  "name":"Winter,",
  "age": 28,
  "distance" : "1 mile away",
  "bio": "dancing is my life.",
  "correctAnswer": "I'll rondversé with you any day.",
  "answer2": "You must be a choir director, because you make my heart sing!",
  "answer3": "You must be a C major scale.. All natural.",
},
{
  "name":"Stevie,",
  "age": 28,
  "distance" : "1 mile away",
  "bio": "Photo major. Looking for models and friends. let’s link and shoot!",
  "correctAnswer": "We can take it slow, and see how things develop.",
  "answer2": "Before you came along, I was just Lipsum. With you, I’d be real content.",
  "answer3": "With you, I'd never stop().",
},
{
  "name":"Spencer,",
  "age": 28,
  "distance" : "1 mile away",
  "bio": "Software engineer working for a design agency. Let me fix your computer lol.",
  "correctAnswer": "Hey, my name's Microsoft. Can I crash at your place tonight?",
  "answer2": "My love for you is like pi... never ending.",
  "answer3": "Our love can cross the Univers.",
},
{
  "name":"Sean,",
  "age": 21,
  "distance" : "2 miles away",
  "bio": "Always at Tompkins Square Park with my dog, Jack. He's my best friend 4life.",
  "correctAnswer": "A day with you would be like an eternity of behind-the-ear scratches.",
  "answer2": "My love for you is like a hairball - I can't hold it in.",
  "answer3": "Are you a cat? Because you're purrrrrfect.",
},
{
  "name":"Peyton,",
  "age": 21,
  "distance" : "2 miles away",
  "bio": "Love acting. My dream is to be on Broadway!",
  "correctAnswer": "Are you that line I screwed up? Because I can’t stop thinking about you.",
  "answer2": "You're like my favorite font, I never get tired of seeing you.",
  "answer3": "If I could rearrange the alphabet, I would put U and I next to each other.",
},
{
  "name":"Graham,",
  "age": 28,
  "distance" : "2 miles away",
  "bio": "Visiting from France for short while! Trying to make new friends.",
  "correctAnswer": "Are you sure you're not a tower? Because Eiffel for you.",
  "answer2": "Are you from Tennessee? Because you're the only ten I See!",
  "answer3": "You must be from Prague, because I can't help but Czech you out.",
},
{
  "name":"Jan,",
  "age": 24,
  "distance" : "3 miles away",
  "bio": "Studying criminal justice!",
  "correctAnswer": "If loving you is a crime, then I'm looking at a life sentence.",
  "answer2": "my Haus is your Haus.",
  "answer3": "Do you believe in love at first sight, or should I walk by again?",
},
{
  "name":"Mitchell,",
  "age": 25,
  "distance" : "3.5 miles away",
  "bio": "Interested in science and biology! currently studying at NYU Stern.",
  "correctAnswer": "Is it getting hot in here? Or is it just our bond forming?",
  "answer2": "Quit Stalin and give me your number.",
  "answer3": "I hope interest rates are low, because I want to invest my time in you.",
},
{
  "name":"Ray,",
  "age": 23,
  "distance" : "2 miles away",
  "bio": "Only looking for nice, humble people. If you're cocky, don't message me.",
  "correctAnswer": "Even if there wasn't gravity on earth, I'd still fall for you.",
  "answer2": "well, HERE I AM. What are your other two wishes?",
  "answer3": "you look ill. You must be suffering from a lack of Vitamin ME.",
},
{
  "name":"Max,",
  "age": 20,
  "distance" : "2 miles away",
  "bio": "signed to NY MODELS. Parsons Fashion Major.",
  "correctAnswer": "Do you know what this shirt is made of? Boyfriend material.",
  "answer2": "I just want to get the Helvetica out of here and run away with you.",
  "answer3": "Are you a 90 degree angle? Cause you are looking right!",
},
{
  "name":"Monroe,",
  "age": 21,
  "distance" : "2 miles away",
  "bio": "i love Harry Potter. I’m definitely Griffindor, wbu? :)",
  "correctAnswer": "You can have the portkey to my heart.",
  "answer2": "Hi. The voices in my head just told me to come talk to you.",
  "answer3": "Am I dead? Because I think I just met an angel.",
},
{
  "name":"Ken,",
  "age": 23,
  "distance" : "2 miles away",
  "bio": "Vegan. THE MEAT INDUSTRY KILLS.",
  "correctAnswer": "I’m willing to give up meat — but I’d never give up you.",
  "answer2": "Your name must be Coca Cola, because you're so-da-licious.",
  "answer3": "If you were a steak you would be well done.",
},
{
  "name":"Louise,",
  "age": 21,
  "bio": "I’m a scorpio. I’m crazy and spontaneous.",
  "correctAnswer": "Wanna exchange CoStars?",
  "answer2": "Do you live on Mars? ‘Cause you look out of this world.",
  "answer3": "Are you the sun? Because you’re the center of my universe.",
},
]
